### PR TITLE
Initial dashboard configs

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
There are a few widgets missing for the ussd dashboard, #54, #55 and #56 need to be resolved before we can add those, so maybe it can be in a separate PR?

**Comment by justinvdm** [comment]
Will make the dashboard changes soon after #55 and #59 land.

**Comment by justinvdm** [comment]
@imsickofmaps ready for review, I think.

**Comment by imsickofmaps** [comment]
@justinvdm I have no idea what these files are meant to be like - shouldn't someone who worked with you on the dashboarding framework who does, do the review?

**Comment by justinvdm** [comment]
@imsickofmaps Erm, good point, sorry about that :)
@hodgestar do you have time to talk a look? Np if you don't, I think we should maybe just land this and see how the dashboards look?

**Comment by hodgestar** [comment]
I'm not sure how thoroughly I've managed to review this, but :+1:.

**Comment by justinvdm** [comment]
@hodgestar thanks :)

**Pull request merged**
