### PR TITLE
Add Directory browsing to the jssandbox

### PR DESCRIPTION
**Pull request by imsickofmaps**
Should implement display of #20 

On completion of display of each sub-category content there should be an End Session

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@smn ready for review

**Comment by smn** [comment]
thanks, will have a look. Just noting the test failure due to a global leak in your JS code somewhere.

**Comment by imsickofmaps** [comment]
@smn yeah - I really should stop ignoring Travis errors as they actually mean something now!

**Comment by smn** [comment]
Am I seeing double?

screenshot_2013_07_17_10_45_am

**Comment by smn** [comment]
:+1:

**Pull request merged**
