### PR TITLE
First request takes 4 seconds to complete, causing timeouts.

### PR DESCRIPTION
**Pull request by smn**
vumi_go

@imsickofmaps is this app making a lot of HTTP calls and can we log them so we can see if that's what's causing this delay?

### CODE REVIEW

**Comment by smn** [comment]
vumi_go

Wow http calls, very latency.

**Comment by imsickofmaps** [comment]
Thanks for doing this - the only other idea I had was to use Q to do parallel promises?

**Comment by smn** [comment]
@imsickofmaps read the commit log and weep. :+1: would be appreciated.

**Comment by smn** [comment]
vumi_go

now takes 25ms to process. Landing because testing.

**Pull request merged**
