### PR TITLE
Allow metric store to be configured

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
The sms and ussd app configs will need to include a field for the metric store once this lands.

**Comment by hodgestar** [comment]
This will require a config update in the conversations that use it, but otherwise :+1: from me.

**Comment by imsickofmaps** [comment]
@justinvdm what does the config now look like?

**Comment by justinvdm** [comment]
@imsickofmaps The config will now need a `metric_store` field. So the actual USSD and SMS conversation configs will look something like this:

``` json
{
...
  "metric_store": "ghr_metrics"
...
}
```

and the QA SMS and USSD conversation configs will look something like:

``` json
{
...
  "metric_store": "ghr_qa_metrics"
...
}
```

That way, we can keep all 4 conversations on the GHR Go account.

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
