### PR TITLE
Fix non-unicode extra

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@justinvdm stop the fruity loops

**Comment by justinvdm** [comment]
:+1:

**Comment by smn** [comment]
This bites us a lot. Maybe we should be happy to drop the unicode enforcement here because everything's going through JSON serialize / deserializing anyway and Riak will happily store all that.

@Hodgestar / @justinvdm thoughts?

**Comment by justinvdm** [comment]
Ya, we need to fix this. Everything is being JSON serialized/deserialized, so I'm happy to drop the enforcement.

**Comment by justinvdm** [comment]
@smn will the contacts model's validation complain about it too though? Can't really remember how that works. If it does, this could be a bit more involved. If its just the contacts resource, then it should be simple.

**Comment by smn** [comment]
I think it should be fine but @hodgestar would know best.

On 6 February 2014 08:42, Justin van der Merwe notifications@github.comwrote:

> @smn https://github.com/smn will the contacts model's validation
> complain about it too though? Can't really remember how that works. If it
> does, this could be a bit more involved. If its just the contacts resource,
> then it should be simply.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/praekelt/go-nike-ghr/pull/64#issuecomment-34296689
> .

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn

**Comment by hodgestar** [comment]
`Dynamic` fields in our Riak models can only store items of a single type. By default that type is `Unicode`.  We could probably switch that to `Json` without writing a migration, but we'd have to be rather careful.

**Comment by hodgestar** [comment]
The other issue with loosening up the type check is that it'd make saving values from a web form more difficult since it'd be tricky to distinguish `5` and `"5"` (for example). There are potentially ways around this though so I don't think we should necessarily let it hold anything up.

**Pull request merged**
